Name = input("Введите имя: ")
Surname = input("Введите фамилию: ")
City = input("Введите город проживания: ")
print("==============================")
print("Вас зовут " + Name, Surname)
print("Вы живёте в городе " + City)